# Generated by Django 3.0.8 on 2020-07-19 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataresponse',
            name='data_tracker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.DataTracker'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dataresponse',
            unique_together={('entry', 'data_tracker')},
        ),
    ]
