# Generated by Django 3.0.8 on 2020-07-20 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20200719_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataresponse',
            name='data_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.DataOption'),
        ),
    ]
