# Generated by Django 3.0.8 on 2020-07-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20200720_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatracker',
            name='color',
            field=models.CharField(default='red', max_length=30),
            preserve_default=False,
        ),
    ]
